#-
#   __ _           _
#  / _(_)_ __   __| |_ __ ___  _   _
# | |_| | '_ \ / _` | '_ ` _ \| | | |
# |  _| | | | | (_| | | | | | | |_| |
# |_| |_|_| |_|\__,_|_| |_| |_|\__, |
#                              |___/
#- from github.com/ngocjohn/hass-config
#
homeassistant:
  customize:
    device_tracker.viet_ngoc_samsung:
      entity_picture: /local/img/samsung-z-flip.png
