#################################################
#                                               #
#                SIDEBAR TEMPLATE               #
#                                               #
#################################################

template:
  - sensor:
      - unique_id: sidebar
        state: template
        attributes:
          time: >
            {% set hours = now().strftime('%H') %} {% set minutes = now().strftime('%M') %} <span class="time">
              {{ hours }}<span class="time-colon">:</span>{{ minutes }}
            </span>
          date: >
            <span class="date">
              {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != None %}
              {%- set days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'] %}
              {%- set months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] %}
              <b>
                {{'ðŸ“†'}} {{ days[now().weekday()] }} â€¢ {{ strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
              </b><br>
                {%- endif %}
            </span>
            <span class="lunar">
              {{'ðŸŒš'}} <b>{{ states.calendar.lunar.attributes.message | replace("/", ". ") }}. 2023</b><br>
            </span>
            <span class="holiday">
              {%- set midnight = today_at() %}
              {%- set event = state_attr('calendar.ceske_statni_svatky', 'start_time') | as_datetime | as_local %}
              {%- set delta = event - midnight %}
              {%- if delta.days == 0 %}
              <b>{{ state_attr('calendar.ceske_statni_svatky', 'message') }}</b>
              {%- endif %}
            </span>
          greet: >
            <span class="greet">
              {%- set time = now().hour %}
              {%- if time <= 1 -%} {{'ðŸ’¤'}} <b>Good night</b>
              {%- elif time <= 3 -%} {{'ðŸ˜´'}} <b>Good night</b>
              {%- elif time <= 5 -%} {{'ðŸ˜ª'}} <b>Good night</b>
              {%- elif time <= 7 -%} {{'ðŸ§ '}} <b>Good morning</b>
              {%- elif time <= 9 -%} {{'ðŸ¤Ÿ'}} <b>Good morning</b>
              {%- elif time <= 10 -%} {{'ðŸ˜˜'}} <b>Good morning</b>
              {%- elif time <= 13 -%} {{'ðŸ˜'}} <b>Good day</b>
              {%- elif time <= 15 -%} {{'ðŸ˜'}} <b>Good day</b>
              {%- elif time <= 17 -%} {{'ðŸ––'}} <b>Good day</b>
              {%- elif time <= 19 -%} {{'ðŸ¤©'}} <b>Good evening</b>
              {%- elif time <= 22 -%} {{'ðŸ¤—'}} <b>Good evening</b>
              {%- elif time <= 23 -%} {{'ðŸ¤«'}} <b>Good night</b>
              {%- else %} {{'ðŸ¤«'}} <b>Good night</b>
              {%- endif -%}
            </span>
          active: >
            {%- set lights = [
              states.light.living_room_floor_lamp,
              states.light.shelly_dimmer,
              states.light.shelly_rgbw_kitchen_led_strip,
              states.light.kitchen_main_light,
              states.light.kitchen_table_light,
              states.light.hood_lighting,
              states.light.bathroom_main_light,
              states.light.bathroom_mirror_light,
              states.light.bedroom_closet_light,
              states.light.bedroom_main_light,
              states.light.shower_room_main_light,
              states.light.shower_room_mirror_light,
              states.switch.lidl_3_gang_socket_l2,
              states.light.aqara_hub,
              states.light.utility_room_light,
              states.light.hallway_light,
              states.light.office_lamp_bulb,
              states.light.office_main_light,
              states.light.office_shelf_led,
              states.light.vocolinc_rpl_188bce_mood_light,
              states.light.office_led_light_strip,
              states.light.bedroom_ripple_mood_light
            ] %}
            <span class="active">
            {%- set lights_on = lights | selectattr('state','eq','on') | list %}
            {%- set lights_name = lights | selectattr('state','eq','on') | map (attribute='name') | join(', ') %}
            {%- if (lights_on | length == 1) -%}
              {{'ðŸ’¡'}} <b>{{ lights_name }} is on</b>
            {%- elif (lights_on | length == 2) -%}
              {{'ðŸ’¡'}} <b>{{ lights_name | regex_replace(',([^,]*)$',' and\\1') }} is on</b>
            {%- elif (lights_on | length > 2) -%}
              {{'ðŸ’¡'}} <b>{{ lights_on | length }} lights on</b>
            {%- else %}
              <b><font color='#4b5254'>Everything is turned off</font></b>
            {%- endif -%}
            </span>
          battery: >
            <span class="battery">
            {%- set ignore_entities = integration_entities('mobile_app') -%}
            {%- set ignore_icloud = integration_entities('icloud') -%}
            {%- set entities = states.sensor
              | rejectattr('attributes.device_class', 'undefined')
              | selectattr('attributes.device_class', 'eq', 'battery')
              | rejectattr('entity_id', 'in', ignore_entities)
              | rejectattr('entity_id', 'in', ignore_icloud)
              | rejectattr('entity_id', 'search', 'low')
              | rejectattr('entity_id', 'search', 'browser')
              | map(attribute = 'entity_id') | list -%}
            {%- for sensor in entities if states(sensor)  != 'unknown' and states(sensor) != 'unavailable' and states(sensor) != 'None' and states(sensor) | int(default=0) <= 20 -%}
            {% if loop.first %}
            {{'ðŸª«'}} Low Baterry {{'ðŸª«'}}  {% else %}, {% endif %}
            <br>{{ state_attr(sensor, 'friendly_name') | string | replace(' percentage', ' ') }} {{ states(sensor) }}%
            {%- endfor %}
            </span>
      - unique_id: wide_timeclock
        state: template
        attributes:
          hour: >
            {% set hours = now().strftime('%H') %} {{ hours }}
          minutes: >
            {% set minutes = now().strftime('%M') %} {{ minutes}}
          day: >
            {{ states.sensor.day_en.state }}
          date: >
            {{'ðŸ“†'}} {{ states.sensor.date_en.state }}
          lunar: >
            {{'ðŸŒš'}} {{ states.calendar.lunar.attributes.message | replace("/", ".") }}
          events: >
            {%- set midnight = today_at() %}
            {%- set event = state_attr('calendar.ceske_statni_svatky', 'start_time') | as_datetime | as_local %}
            {%- set delta = event - midnight %}
            {%- if delta.days == 0 %}
            <div class="marquee">{{ state_attr('calendar.ceske_statni_svatky', 'message') }}</div>
            {% else %}
            {% set time = now().hour %}
            {%- if time <= 1 -%} {{'ðŸ’¤'}} Good night
            {%- elif time <= 3 -%} {{'ðŸ˜´'}} Good night
            {%- elif time <= 5 -%} {{'ðŸ˜ª'}} Good night
            {%- elif time <= 7 -%} {{'ðŸ§ '}} Good morning
            {%- elif time <= 9 -%} {{'ðŸ¤Ÿ'}} Good morning
            {%- elif time <= 10 -%} {{'ðŸ˜˜'}} Good morning
            {%- elif time <= 13 -%} {{'ðŸ˜'}} Good day
            {%- elif time <= 15 -%} {{'ðŸ˜'}} Good day
            {%- elif time <= 17 -%} {{'ðŸ––'}} Good day
            {%- elif time <= 19 -%} {{'ðŸ¤©'}} Good evening
            {%- elif time <= 22 -%} {{'ðŸ¤—'}} Good evening
            {%- elif time <= 23 -%} {{'ðŸ¤«'}} Good night
            {%- else %} {{'ðŸ¤«'}} Good night
            {%- endif -%}
            {%- endif %}
      - unique_id: sidebar_time
        state: template
        attributes:
          time: >
            {% set hours = now().strftime('%H') %} {% set minutes = now().strftime('%M') %}<span class="time">{{ hours }}<span class="time-colon">:</span>{{ minutes }}</span>
          date: >
            <div id="date">
            <span class="date">
            {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != None %}
            {%- set days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'] %}
            {%- set months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] %}
            <b>
            {{'ðŸ“†'}}&nbsp;{{ days[now().weekday()] }}&nbsp;â€¢&nbsp;{{ strptime(states('sensor.date'), '%Y-%m-%d').day }}&nbsp;{{ months[now().month-1] }}&nbsp;{{'ðŸŒš'}}&nbsp;{{ states.calendar.lunar.attributes.message | replace("/", ". ") }}
            </b>
            {%- endif %}
            </span>
            <div>
            <span class="holiday">
              {%- set midnight = today_at() %}
              {%- set event = state_attr('calendar.ceske_statni_svatky', 'start_time') | as_datetime | as_local %}
              {%- set delta = event - midnight %}
              {%- if delta.days == 0 %}
              <b>{{ state_attr('calendar.ceske_statni_svatky', 'message') }}</b>
              {%- endif %}
            </span>
            </div>
